jwt_secret: ''
oauth:
  google:
    client_id: ''
    client_secret: ''
    redirect_url: ''
    scopes:
      - 'profile'
      - 'email'
database:
  host: 'localhost'
  port: 5432
  username: ''
  password: ''
  name: 'sds_status'
  ssl_mode: false
