port: 8081
prometheus_metrics: true

checks:
  - input:
      type: "HTTP"
      value: "GET"
    output:
      type: "status_code"
      value: "200"
    target:
      type: "url"
      value: "https://google.com"
    name: "test-http-check-google"
    interval: 10
    timeout: 10

  - input:
      type: "HTTP"
      value: "GET"
    output:
      type: "status_code"
      value: "200"
    target:
      type: "url"
      value: "https://sdslabs.co"
    name: "test-http-check-sdslabs"
    interval: 5
    timeout: 10
