# Configuration file for status application server.

# JWT Secret to encrypt tokens.
jwt_secret: ''

# OAuth Providers.
oauth:
  # Google
  google:
    client_id: ''
    client_secret: ''
    redirect_url: ''
    scopes:
      - 'profile'
      - 'email'
      - 'openid'

# PostgreSQL database.
database:
  host: '127.0.0.1'
  port: 5432
  username: ''
  password: ''
  name: ''
  ssl_mode: false
